extends: racs_low2_flux15_ds4
observation_id: racs_low2_45as_flux15_ds4

datasets:
  catalogue: racs_low2_45as_catalogue

args:
  racs_epoch: low2-45as

mask:
  config: workflow/configs/observations/masks/racs_low2_25as_mask.yaml
