datasets:
  racs_mid1_catalogue:
    type: file
    description: RACS mid1 source catalogue used for the reference observation.
    sha256: b0a90cacd3c24e552c00c422f82a1e53f8d53824a50bdd04b03ce66b4ffa998e
    source: Internal file

  racs_mid1_paf_temperatures:
    type: file_collection
    description: Per-antenna ASKAP PAF temperatures used for RACS mid1.
    manifest: ../data-manifests/racs_mid1_paf_temperatures.yaml
    source: Internal file

  racs_mid1_noise_maps:
    type: file_collection
    description: RACS MID1 survey noise map used by the flux-error lookup.
    manifest: ../data-manifests/racs_mid1_noise_maps.yaml
    source: Internal file

  racs_low3_catalogue:
    type: file
    description: RACS low3 source catalogue used for the reference observation.
    sha256: 7fa137fd34e4b0ba28741dbc2a01dfbb9d98da57ddf65dc1a37a190e421308f1
    source: Internal file

  racs_low3_paf_temperatures:
    type: file_collection
    description: Per-antenna ASKAP PAF temperatures used for RACS low3.
    manifest: ../data-manifests/racs_low3_paf_temperatures.yaml
    source: Internal file

  racs_low3_noise_maps:
    type: file_collection
    description: RACS LOW3 survey noise map used by the flux-error lookup.
    manifest: ../data-manifests/racs_low3_noise_maps.yaml
    source: Internal file

  racs_low2_catalogue:
    type: file
    description: RACS low2 source catalogue used for the reference observation.
    sha256: b8a5711f6168522b0064cb757661eba1e987308afa3239cbfc53b4fe04de3f81
    source: Internal file

  racs_low2_25as_catalogue:
    type: file
    description: RACS low2 25 arcsec patched source catalogue used for the reference observation.
    sha256: b86781c93026e49e33ee97b43c180d641774f6c331936c8c21051becaf469efc
    source: Internal file

  racs_low2_45as_catalogue:
    type: file
    description: RACS low2 45 arcsec patched source catalogue used for the reference observation.
    sha256: ad9f05a76641e552d31b46ef2b6346b6c5bfa437c6c658e211342a36fcc98405
    source: Internal file

  racs_low2_paf_temperatures:
    type: file_collection
    description: MID1 per-antenna ASKAP PAF temperatures reused for RACS low2.
    manifest: ../data-manifests/racs_low2_paf_temperatures.yaml
    source: Internal file

  racs_low2_noise_maps:
    type: file_collection
    description: RACS LOW3 survey noise map used by the flux-error lookup.
    manifest: ../data-manifests/racs_low2_noise_maps.yaml
    source: Internal file
